apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: arbeidsgiver-redirect-forside
  namespace: fager
  labels:
    team: fager
spec:
  image: '{{{image}}}'
  ingresses:
    - 'https://arbeidsgiver.dev.nav.no/'
  liveness:
    path: /internal/ok
  readiness:
    path: /internal/ok
