name: ci/cd
on:
  push:
  workflow_dispatch:

jobs:
  cicd:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
      packages: 'write'
    steps:
      - uses: actions/checkout@v3

      - uses: nais/docker-build-push@v0
        id: dockerpush
        with:
          team: fager
          tag: ${{ github.sha }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Deploy dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          IMAGE: ${{ steps.dockerpush.outputs.image }}
          CLUSTER: dev-gcp
          RESOURCE: nais-dev.yaml
          PRINT_PAYLOAD: true
          VAR: commit=${{ github.sha }}

      - name: Deploy prod-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          IMAGE: ${{ steps.dockerpush.outputs.image }}
          CLUSTER: prod-gcp
          RESOURCE: nais-prod.yaml
          PRINT_PAYLOAD: true
          VAR: commit=${{ github.sha }}
