name: ci/cd
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1' # bygg nytt image hver mandag morgen

jobs:
  cicd:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
      packages: 'write'
    steps:
      - uses: actions/checkout@v4

      - uses: nais/docker-build-push@v0
        id: dockerpush
        with:
          team: fager
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Deploy dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais-dev.yaml
          PRINT_PAYLOAD: true
          VAR: image=${{ steps.dockerpush.outputs.image }}

      - name: Deploy prod-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais-prod.yaml
          PRINT_PAYLOAD: true
          VAR: image=${{ steps.dockerpush.outputs.image }}
